services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fintech-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres_payments:
    image: postgres:16
    container_name: fintech-postgres-payments
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: paymentsdb
    ports:
      - "5433:5432"
    volumes:
      - pg_payments:/var/lib/postgresql/data

  postgres_ledger:
    image: postgres:16
    container_name: fintech-postgres-ledger
    environment:
      POSTGRES_USER: ledger
      POSTGRES_PASSWORD: ledger
      POSTGRES_DB: ledgerdb
    ports:
      - "5434:5432"
    volumes:
      - pg_ledger:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: fintech-keycloak
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    volumes:
      - ./fintech-realm.json:/opt/keycloak/data/import/fintech-realm.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

volumes:
  pg_payments:
  pg_ledger:
